default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:
  timeout: 5000

development:
  <<: *default
  database: test_app_development

framgia_staging:
  <<: *default
  username: root
  database: test_app_stagging

production:
  <<: *default
  username: root
  database: test_app_production

test:
  <<: *default
  database: test_app_test
